Repository rrweb-io/rrweb, pull requests merged in 2023-02, with the labels that each got.

#1092 fix: regression of issue: ShadowHost can't be a string (issue 941)
  packages/rrweb/src/record/mutation.ts
  packages/rrweb/src/utils.ts
  packages/rrweb/test/util.test.ts
Labels: bug, 2.0, regression

#1109 add option to record on DOMContentLoaded event
  guide.md
  guide.zh_CN.md
  packages/rrweb/src/record/index.ts
  packages/rrweb/src/types.ts
  packages/rrweb/test/__snapshots__/integration.test.ts.snap
  packages/rrweb/test/integration.test.ts
  packages/rrweb/test/utils.ts
Labels: 2.0

#1095 fix duplicated shadow dom
  .changeset/loud-seals-raise.md
  package.json
  packages/rrweb-snapshot/src/rebuild.ts
  packages/rrweb-snapshot/src/utils.ts
  packages/rrweb-snapshot/test/utils.test.ts
  packages/rrweb/package.json
  packages/rrweb/src/record/index.ts
  packages/rrweb/src/record/shadow-dom-manager.ts
  yarn.lock
Labels: bug, 2.0
